workspace:
        base:/server/ServerPR
        path:.

pipeline:
        build:
                image: golang
                environment:
                - KEY=VALUE
                secrets: [key1, key2]
                commands:
                - echo $$KEY
                - pwd       
                - ls
                - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .
                - ./app
